apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: memorystack

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - server-deployment.yaml
  - web-deployment.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: memorystack

images:
  - name: memorystack/server
    newTag: latest
  - name: memorystack/web
    newTag: latest
